import { Theme } from "../common.slint";

export global BarialState {
    in property <int> fps: 0;
    in property <string> user: "";
    in property <string> server_name: "";
}

export component Barial inherits Rectangle {
    width: 100%;
    height: 25px; 
    background: rgba(0, 0, 0, 0.85);

    VerticalLayout {
        alignment: LayoutAlignment.center;
        width: 100%;
        height: 100%;
        padding-left: 20px;
        padding-right: 20px;

        HorizontalLayout {
            width: 100%;
            alignment: LayoutAlignment.space-between;
            HorizontalLayout {
                spacing: 20px;
                HorizontalLayout {
                    spacing: 5px;
                    Image {
                        source: @image-url("../../assets/icons/lock.svg");
                        width: 16px;
                        height: 16px;
                        colorize: Theme.text_secondary_color;
                    }
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: "MRDP";
                            color: Theme.text_secondary_color;
                            font-size: 14px;
                        }
                    }
                }
                HorizontalLayout {
                    Text {
                        text: BarialState.user;
                        color: Theme.text_secondary_color;
                        font-size: 14px;
                    }
                    Text {
                        text: "@";
                        color: Theme.text_secondary_color;
                        font-size: 14px;
                        visible: BarialState.user != "" && BarialState.server_name != "";
                    }
                    Text {
                        text: BarialState.server_name;
                        color: Theme.text_secondary_color;
                        font-size: 14px;
                    }
                }
            }
            HorizontalLayout {
                Text {
                    text: "FPS: ";
                    color: Theme.text_secondary_color;
                    font-size: 14px;
                }
                Text {
                    text: BarialState.fps;
                    color: Theme.text_secondary_color; 
                    font-size: 14px;
                }
            }
        }
    }
}