export component Footer inherits HorizontalLayout {
    padding: 10px;
    alignment: LayoutAlignment.space-between;
    Text {
        text: "©2023 MahitM Product. All Rights Reserved.";
        color: rgba(89, 89, 89); 
        horizontal-alignment: TextHorizontalAlignment.right;
    }
    Text {
        text: "Build Version: 0.0.1";
        color: rgba(89, 89, 89); 
        horizontal-alignment: TextHorizontalAlignment.right;
    }
}