import { GlobalVars } from "../common.slint";

export component Footer inherits HorizontalLayout {
    padding: 10px;
    alignment: LayoutAlignment.space-between;
    Text {
        text: "©2024 MahitM Product. All Rights Reserved.";
        color: rgba(89, 89, 89); 
        font-size: 12px;
        horizontal-alignment: TextHorizontalAlignment.right;
    }
    Text {
        text: "Build Version: " + GlobalVars.app-version;
        color: rgba(89, 89, 89); 
        font-size: 12px;
        horizontal-alignment: TextHorizontalAlignment.right;
    }
}