import { MrialButton, MrialTextInput, Theme, MrialHeader, MrialSubHeader, ButtonType } from "../common.slint";

export global CreateServerFunctions {
    pure callback add(
        /* server name */ string, 
        /* ip address */ string, 
        /* port */ string,
        /* username */ string,
        /* password */ string
        );
}

export component CreateServer inherits VerticalLayout {
    alignment: LayoutAlignment.start;
    spacing: 15px;

    VerticalLayout {
        spacing: 5px;

        MrialHeader {
            text: "Add Remote Server";
        }
        MrialSubHeader {
            text: "Get ready to stream your remote server in real-time with ultra low-latency.";
        }
    }
    Rectangle {
        height: 1px;
        width: parent.width - parent.padding * 2;
        background: Theme.secondary-border-color;
    }
    HorizontalLayout {
        spacing: 10px;
        name := MrialTextInput {
            placeholder: "Server Name";
            input-type: InputType.text;
            width: 125px;
            height: 30px;
        }
        ip_addr := MrialTextInput {
            placeholder: "IP Address";
            input-type: InputType.text;
            width: 125px;
            height: 30px;
        }
        port := MrialTextInput {
            placeholder: "Port";
            width: 125px;
            height: 30px;
            input-type: InputType.number;
        }
    }
    HorizontalLayout {
        spacing: 10px;
        username := MrialTextInput {
            placeholder: "Username";
            input-type: InputType.text;
            width: 125px;
            height: 30px;
        }
        pass := MrialTextInput {
            placeholder: "Password";
            input-type: InputType.password;
            width: 125px;
            height: 30px;
        }
    }
    MrialButton {
        width: 125px;
        has-icon: true;
        icon:  @image-url("../../assets/icons/server.svg");
        label: "Add Server";
        disabled: name.value == "" || 
                  ip-addr.value == "" || 
                  port.value == "" || 
                  username.value == "" || 
                  pass.value == "";
        type: ButtonType.gradient;
        clicked => {
            if (name.value == "" || 
                ip-addr.value == "" || 
                port.value == "" || 
                username.value == "" || 
                pass.value == "") {
                return;
            }

            CreateServerFunctions.add(
                name.value, 
                ip-addr.value, 
                port.value,
                username.value,
                pass.value
            );

            name.value = "";
            ip-addr.value = "";
            port.value = "";
            username.value = "";
            pass.value = "";
        }
    }
}