import { MrialButton, MrialTextInput, Theme, MrialHeader, MrialSubHeader } from "../common.slint";

export global CreateServerFunctions {
    pure callback add(
        /* server name */ string, 
        /* ip address */ string, 
        /* port */ string,
        /* username */ string,
        /* password */ string
        );
}

export component CreateServer inherits VerticalLayout {
    alignment: LayoutAlignment.start;
    spacing: 15px;

    VerticalLayout {
        spacing: 5px;

        MrialHeader {
            text: "Add Remote Server";
        }
        MrialSubHeader {
            text: "Get ready to stream your remote server in real-time with ultra low-latency.";
        }
    }
    Rectangle {
        height: 1px;
        width: parent.width - parent.padding * 2;
        background: Theme.secondary-border-color;
    }
    HorizontalLayout {
        spacing: 10px;
        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Server Name";
                color: Theme.text-primary-color;
            }
            name := MrialTextInput {
                input-type: InputType.text;
                width: 125px;
                height: 30px;
            }
        }
        VerticalLayout {
            spacing: 5px;
            Text {
                text: "IP Address";
                color: Theme.text-primary-color;
            }
            ip_addr := MrialTextInput {
                input-type: InputType.text;
                width: 125px;
                height: 30px;
            }
        }
        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Port";
                color: Theme.text-primary-color;
            }
            port := MrialTextInput {
                width: 125px;
                height: 30px;
                input-type: InputType.number;
            }
        }
    }
    HorizontalLayout {
        spacing: 10px;
        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Username";
                color: Theme.text-primary-color;
            }
            username := MrialTextInput {
                input-type: InputType.text;
                width: 125px;
                height: 30px;
            }
        }
        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Password";
                color: Theme.text-primary-color;
            }
            pass := MrialTextInput {
                input-type: InputType.password;
                width: 125px;
                height: 30px;
            }
        }
    }
    MrialButton {
        width: 125px;
        has-icon: true;
        icon:  @image-url("../../assets/icons/server.svg");
        label: "Add Server";
        clicked => {
            CreateServerFunctions.add(
                name.value, 
                ip-addr.value, 
                port.value,
                username.value,
                pass.value
            );
        }
    }
}