import { Screen, Theme , MrialButton, ButtonType , MrialTextInput, MrialHeader , MrialSubHeader} from "../common.slint";
import { Button , VerticalBox , ProgressIndicator} from "std-widgets.slint";
import { Server, IServer, ServerFunctions } from "../components/server.slint";
import { Footer } from "../components/footer.slint";
import { CreateServer } from "create_server.slint";

export global HomePageAdapter {
    in-out property <[IServer]> servers: [];
}

component NavItem inherits Rectangle {
    in property <string> name;
    in property <bool> active;
    in property <image> icon;

    callback clicked();

    height: 35px;
    background: touch-area.has-hover && !active ? rgba(255,255,255,0.05) : rgba(0,0,0,0);
    border-radius: 7.5px;
    animate background { duration: 0.15s; }

    touch_area := TouchArea {
        mouse-cursor: MouseCursor.pointer;
        clicked => { clicked();  }
    }

    HorizontalLayout {
        padding: 5px;
        padding-left: 14px;
        spacing: 7.5px;
        VerticalLayout {
            alignment: LayoutAlignment.center;
            Image {
                width: 20px;
                height: 20px;
                source: icon;
                colorize: Theme.text-primary-color;
                opacity: active ? 1.0 : 0.8;
            }
        }
        Text {
            text: name; 
            font-size: 12px;
            font-weight: 500;
            opacity: active ? 1.0 : 0.8;
            color: Theme.text-primary-color;
            vertical-alignment: TextVerticalAlignment.center;
        }
    }
}

export component HomeScreen inherits Screen {
    in-out property <int> nav_page: 1;

    HorizontalLayout {
        navbar := Rectangle {
            width: 150px;
            height: 100%;
            background: Theme.bg-secondary-color;
            VerticalLayout {
                width: parent.width;
                padding: 10px;
                padding-top: 24px;
                spacing: 15px;

                MrialButton {
                    border-radius: 7.5px;
                    drop-shadow-blur: 10px;
                    drop-shadow-color: rgba(0,0,0,0.15);
                    width: parent.width - parent.padding * 2;
                    label: "Add Server";
                    type: ButtonType.basic;
                    border-color: Theme.secondary-border-color;
                    border-width: 2px;
                    icon:  @image-url("../../assets/icons/plus.svg");
                    has-icon: true;
                    clicked => { root.nav-page = 0; }
                }
                Rectangle {
                    height: 1px;
                    width: parent.width - parent.padding * 2;
                    background: Theme.secondary-border-color;
                }
                Rectangle {
                    nav_item_overlay := Rectangle {
                        opacity: root.nav-page != 0 ? 1.0 : 0.0;
                        y: (root.nav_page - 1) * 40px;
                        width: parent.width;
                        height: 35px;
                        background: rgba(255,255,255,0.05);
                        border-radius: 7.5px;
                        animate y { duration: 0.25s; easing: ease-in-out; }
                        Rectangle {
                            x: 5px; 
                            y: parent.height / 2 - self.height / 2; 
                            width: 3px; 
                            height: 14px; 
                            border-radius: 2px;
                            background: @linear-gradient(180deg, Theme.bg-primary-brush-end 0%, Theme.bg-primary-brush-end 100%);
                        }
                    }
                    VerticalLayout {
                        spacing: 5px;
                        NavItem {
                            in property <int> nav_page: 1;
                            active: root.nav_page == self.nav-page;
                            name: "Servers";             
                            icon: @image-url("../../assets/icons/server_stack.svg");
                            clicked => { root.nav_page = self.nav-page; }
                        }
                        NavItem {
                            in property <int> nav_page: 2;
                            active: root.nav_page == self.nav-page;
                            name: "Hosting";
                            icon: @image-url("../../assets/icons/globe.svg");
                            clicked => { root.nav_page = self.nav-page; }
                        } 
                    }
                }
            }
        }
        content := VerticalLayout {
            width: parent.width - navbar.width;

            Rectangle {
                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    visible: nav_page == 1; 
                    padding: 15px;
                    spacing: 15px;

                    VerticalLayout {
                        spacing: 5px;

                        MrialHeader {
                            text: "Remote Servers";
                        }
                        MrialSubHeader {
                            text: "Connect to begin real-time, ultra low-latency streaming.";
                        }
                    }
                    Rectangle {
                        height: 1px;
                        width: parent.width - parent.padding * 2;
                        background: Theme.secondary-border-color;
                    }

                    HorizontalLayout {
                        spacing: 10px;
                        
                        for server in HomePageAdapter.servers: Server {
                            server: server;
        
                            connect => {
                                root.set_current_subpage(2);
                                ServerFunctions.connect(server.name);
                            }
                        }
                    }
                }
                VerticalLayout {
                    padding: 15px;
                    visible: nav_page == 0;
                    spacing: 10px;
                    
                    CreateServer {}
                }
            }            
            Footer {}
        }
    }
}