import { Screen, MrialTextInput , MrialButton, Theme } from "../common.slint";
import { VerticalBox , Button , HorizontalBox} from "std-widgets.slint";
import { Footer } from "../components/footer.slint";

export component LoginScreen inherits Screen {
    in property <length> window_height;
    padding: 0;

    VerticalLayout {
        alignment: LayoutAlignment.space-between;
        padding: 0;
        Rectangle {
            // Rectangle {
            //     height: window_height - 32px;
            //     drop-shadow-color: Theme.drop_shadow_color;
            //     drop-shadow-blur: 15px;
            //     border-color: rgb(29, 29, 29);
            //     border-width: 3px;
            //     border-radius: 10px;
            //     clip: true;
            //     width: l_desk.width;
            //     x: 0px;
            //     y: (window_height - 32px) / 2 - self.height / 2;

            //     l_desk := Image {
            //         height: window_height - 32px; 
            //         source: @image-url("../../assets/imgs/left_desk.png");
            //     }
            // }
            // Rectangle {
            //     height: window_height - 32px;
            //     drop-shadow-color: Theme.drop_shadow_color;
            //     drop-shadow-blur: 15px;
            //     border-color: rgb(29, 29, 29);
            //     border-width: 3px;
            //     border-radius: 10px;
            //     clip: true;
            //     width: r_desk.width;
            //     x: parent.width - self.width;
            //     y: (window_height - 32px) / 2 - self.height / 2;

            //     r_desk := Image {
            //         height: window_height - 32px; 
            //         source: @image-url("../../assets/imgs/right_desk.png");
            //     }
            // }
            Rectangle {
                x: parent.width / 2 - self.width / 2;
                y: window_height / 2 - self.height / 2;
                width: 275px;
                height: 350px;
                drop-shadow-color: Theme.drop_shadow_color;
                drop-shadow-blur: 15px;
                background: rgba(20, 20, 20, 1.0);
                border-color: rgb(29, 29, 29);
                border-width: 3px;
                border-radius: 10px;
                VerticalLayout{
                    padding: 25px;
                    alignment: LayoutAlignment.space-between;
                    VerticalLayout {
                        width: parent.width - parent.padding * 2;
                        Text {
                            text: "MRIAL";
                            font-family: "Inknut Antiqua";
                            font-weight: 900;
                            font-size: 40px;
                            color: white;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            height: self.preferred-height;
                        }
                        VerticalLayout {
                            spacing: 10px;
                            VerticalLayout {
                                spacing: 3px;
                                Text {
                                    text: "Username";
                                    color: rgba(89, 89, 89);
                                }
                                MrialTextInput {
                                    width: parent.width;
                                    height: 35px; 
                                }
                            }
                            VerticalLayout {
                                spacing: 3px;
                                Text {
                                    text: "Password";
                                    color: rgba(89, 89, 89);
                                }
                                MrialTextInput {
                                    width: parent.width;
                                    input-type: InputType.password;
                                    height: 35px; 
                                }
                            }
                            MrialButton {
                                label: "Continue";
                            }
                        }
                    }

                    text_container := TouchArea {
                        mouse-cursor: MouseCursor.pointer;
                        clicked => {
                            root.set_current_subpage(1);
                        }
                        max-height: text.preferred-height;
                        text := Text {
                            text: "Continue Decentralized";
                            font-size: 12px;
                            color: text_container.has-hover ? rgba(100, 100, 100) : rgba(89, 89, 89);
                            animate color { duration: 0.25s; }
                        }
                    }
                }
            }   
        }
        Footer {}
    }
}