import { Screen, MrialTextInput , MrialButton} from "../common.slint";
import { VerticalBox , Button , HorizontalBox} from "std-widgets.slint";
import { Footer } from "../components/footer.slint";

export component LoginScreen inherits Screen {
    in property <length> window_height;
    padding: 0;

    VerticalLayout {
        alignment: LayoutAlignment.space-between;
        padding: 0;
        Image {
            source: @image-url("../../assets/imgs/your_name.jpeg");
            Rectangle {
                x: parent.width / 2 - self.width / 2;
                y: window_height / 2 - self.height / 2;
                width: 275px;
                height: 350px;
                background: rgba(20, 20, 20, 1.0);
                border-color: rgb(29, 29, 29);
                border-width: 3px;
                border-radius: 10px;
                VerticalLayout{
                    padding: 25px;
                    alignment: LayoutAlignment.space-between;
                    VerticalLayout {
                        width: parent.width - parent.padding * 2;
                        Text {
                            text: "MRIAL";
                            font-family: "Inknut Antiqua";
                            font-weight: 900;
                            font-size: 40px;
                            color: white;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            height: self.preferred-height;
                        }
                        VerticalLayout {
                            spacing: 10px;
                            VerticalLayout {
                                spacing: 3px;
                                Text {
                                    text: "Username";
                                    color: rgba(89, 89, 89);
                                }
                                MrialTextInput {
                                    width: parent.width;
                                    height: 35px; 
                                }
                            }
                            VerticalLayout {
                                spacing: 3px;
                                Text {
                                    text: "Password";
                                    color: rgba(89, 89, 89);
                                }
                                MrialTextInput {
                                    width: parent.width;
                                    input-type: InputType.password;
                                    height: 35px; 
                                }
                            }
                            MrialButton {
                                label: "Continue";
                            }
                        }
                    }

                    text_container := TouchArea {
                        mouse-cursor: MouseCursor.pointer;
                        clicked => {
                            root.set_current_subpage(1);
                        }
                        max-height: text.preferred-height;
                        text := Text {
                            text: "Continue Decentralized";
                            font-size: 12px;
                            color: text_container.has-hover ? rgba(100, 100, 100) : rgba(89, 89, 89);
                            animate color { duration: 0.25s; }
                        }
                    }
                }
            }   
        }
        Footer {}
    }
}