import { Screen, Theme } from "../common.slint";
import { VerticalBox, Button } from "std-widgets.slint";
import { MrialButton, ButtonType } from "../common.slint";
import { ServerFunctions } from "../components/server.slint";
import { ControlPanel } from "../components/control_panel.slint";
import { Barial } from "../components/barial.slint";

export global VideoFunctions {
    pure callback mouse_move(/* x */ length, /* y */ length, /* pressed */ bool);
    pure callback click(/* x */ length, /* y */ length, /* button */ PointerEventButton);
    pure callback modifiers_pressed(/* control */ bool, /* shift */ bool, /* alt */ bool, /* meta */ bool);
    pure callback key_pressed(KeyEvent);
    pure callback key_released(KeyEvent);
    pure callback scroll(/* x */ length, /* y */ length);
}

export global VideoState {
    in property <bool> connected: false;
    in property <string> error_message: "";
}

export component VideoScreen inherits Screen {
    in property <image> video-frame <=> image.source;
    in-out property <bool> cp_button_attached: false;
    property<duration> loading_animation_duration: 1500ms;

    private property <length> prev_x: 0;
    private property <length> prev_y: 0;

    background: black;

    image_container := VerticalBox {
        padding: 0;
        image := Image {
            image-rendering: ImageRendering.pixelated;
            padding: 0;
            // opacity: VideoState.connected ? 1 : 0.75;
            // animate opacity { duration: 150ms; }
            video_ta := TouchArea {
                clicked => {
                    if (video_ta.mouse-x > control_panel_button.x && 
                        video_ta.mouse-x < control_panel_button.x + control_panel_button.width && 
                        video_ta.mouse-y > control_panel_button.y && 
                        video_ta.mouse-y < control_panel_button.y + control_panel_button.height 
                    ) {
                        if (control-panel.visible) {
                            control_panel.visible = false; 
                        } else { // if (cp_button_attached == false) {
                            control_panel.visible = true; 
                        }
                    } 
                }
                scroll-event(event) => {
                    VideoFunctions.scroll(event.delta-x, event.delta-y);
                    accept
                }
                pointer-event(event) => {
                    if (video_ta.mouse-x >= control_panel_button.x && 
                        video_ta.mouse-x <= control_panel_button.x + control_panel_button.width && 
                        video_ta.mouse-y >= control_panel_button.y && 
                        video_ta.mouse-y <= control_panel_button.y + control_panel_button.height
                    ) {
                        if (event.kind == PointerEventKind.up) {
                            cp_button_attached = false; 
                        }
                    } else if (event.kind == PointerEventKind.up) {
                        
                        VideoFunctions.click(video_ta.mouse-x, video_ta.mouse-y, event.button);
                    } else if (event.kind == PointerEventKind.move) {
                        if (prev_x == video_ta.mouse-x && prev_y == video_ta.mouse-y) {
                            return;
                        }
                        
                        VideoFunctions.mouse_move(video_ta.mouse-x, video_ta.mouse-y, false);

                        prev_x = video_ta.mouse-x;
                        prev_y = video_ta.mouse-y;
                    }
                }
                moved => {
                    if (video_ta.mouse-x >= control_panel_button.x && 
                        video_ta.mouse-x <= control_panel_button.x + control_panel_button.width && 
                        video_ta.mouse-y >= control_panel_button.y && 
                        video_ta.mouse-y <= control_panel_button.y + control_panel_button.height && self.pressed) {
                            cp-button-attached = true;
                    }

                    if (cp-button-attached) {
                        control_panel_button.x = video_ta.mouse-x - control_panel_button.width / 2;
                        control_panel_button.y = video_ta.mouse-y - control_panel_button.height / 2;
                        return;
                    }

                    VideoFunctions.mouse_move(video_ta.mouse-x, video_ta.mouse-y, self.pressed);
                }
            }
            overlay := Rectangle {
                width: 100%;
                height: 100%;
                background: VideoState.connected ? rgba(0, 0, 0, 0) : rgba(0, 0, 0, 0.35);
                animate background { duration: 250ms; }
            }
            status_bar := Barial {
                x: 0; 
                y: 0; 
                visible: control-panel.visible;
            }
            Rectangle {
                x: parent.width / 2 - self.width / 2;
                y: parent.height / 2 - self.height / 2;  
                visible: !VideoState.error_message.is-empty;
                HorizontalLayout {
                    alignment: LayoutAlignment.center;
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: VideoState.error_message;
                            font-size: 15px;
                            color: orange; 
                        }
                    }
                }
            }
            status := Rectangle {
                x: parent.width / 2 - self.width / 2;
                y: parent.height / 2 - self.height / 2;  
                visible: !VideoState.connected && VideoState.error_message.is-empty;
                HorizontalLayout {
                    width: 300px;
                    height: 32px;
                    spacing: 10px;
                    Image {
                        source: @image-url("../../assets/icons/spinner.png");
                        width: 32px;
                        height: 32px;
                        rotation-angle: VideoState.connected ? 0deg : 360deg * animation-tick() / loading_animation_duration;
                    }
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: "Establishing MRDP Secure Tunnel";
                            font-size: 15px;
                            color: white; 
                        }
                    }
                }
            }
            control_panel := ControlPanel {
                x: control_panel_button.x + control_panel_button.width + 10px;
                y: control-panel-button.y;

                disconnect => {
                    root.set_current_subpage(1);
                    control_panel.visible = false; 
                }
            }

            control_panel_button := Rectangle {
                x: 0px; 
                y: 0px; 
                width: 35px;
                height: 35px;
                border-radius: 7.5px;
                border-width: 1px;
                // border-color: control-panel.visible ? 
                //     Theme.secondary-border-color : 
                //     Theme.bg-secondary-color;
                border-color: Theme.bg-secondary-color;
                background: Theme.bg-primary-color;
                clip: true;
                // animate border-color { duration: 150ms; }

                Image {
                    source: @image-url("../../assets/imgs/logo_x128t.png");
                    width: parent.width;
                    height: parent.height;
                }
            }
        }
    }
}