[workspace]
resolver = "2"
members = [
    "mrial_player",
    "mrial_server",
    "libs/mrial_proto", 
    "libs/mrial_fs"
]

exclude = [ "libs" ]

[workspace.package]
version = "0.1.19"
authors = ["Mahit Mehta", "Marco Ngai"]
license = "GPL-3.0-only"
edition = "2021"
