import { Screen, Theme } from "common.slint";
import { Button , VerticalBox } from "std-widgets.slint";
import { Server } from "components/server.slint";
import { VideoFunctions } from "video.slint";

export component HomeScreen inherits Screen {
    HorizontalLayout {
        Rectangle {
            width: 150px;
            height: 100%;
            background: Theme.bg-secondary-color;
        }
        GridLayout {
            spacing: 10px;
            padding: 15px;

            Row {
                Server {
                    clicked => {
                        root.set_current_subpage(2);
                        VideoFunctions.connect();
                    }
                }
                Server {
                    clicked => {
                        root.set_current_subpage(2);
                    }
                }
            }
        }
    }
}