import "../assets/fonts/Inknut_Antiqua/InknutAntiqua-Bold.ttf";

import { VerticalBox, Button } from "std-widgets.slint";
import { VideoScreen, VideoFunctions } from "video.slint";
import { LoginScreen } from "login.slint";

export { VideoFunctions }

export component MainWindow inherits Window {
    in-out property <int> current-subpage: 0;
    in-out property <image> video-frame;

    min-width: 700px;
    min-height: 500px;

    title: "MRIAL";
    padding: 0;

    forward-focus: key-handler;
    key-handler := FocusScope {
        key-pressed(event) => {
            VideoFunctions.key_pressed(event);
            accept
        }
        key-released(event) => {
            VideoFunctions.key-released(event);
            accept
        }
    }

    LoginScreen {
        window-height: parent.height;
        set_current_subpage(page) => { root.current-subpage = page }
        back => { root.current-subpage = 0 }
        animate y { duration: 500ms; easing: ease-in-out; }
    }

    VideoScreen {
        video-frame: root.video-frame;

        back => { root.current-subpage = 0 }
        y: root.current-subpage == 1 ? 0 : parent.height + parent.y + 2px;
        animate y { duration: 500ms; easing: ease-in-out; }
    }
}