import "../assets/fonts/Inknut_Antiqua/InknutAntiqua-Bold.ttf";

import { VerticalBox, Button } from "std-widgets.slint";
import { VideoScreen, VideoFunctions, VideoState } from "screens/video.slint";
import { BarialState } from "components/barial.slint";
import { ControlPanelAdapter, ControlPanelFunctions } from "components/control_panel.slint";
import { LoginScreen } from "screens/login.slint";
import { HomeScreen, HomeAdapter } from "screens/home.slint";
import { CreateServerFunctions } from "screens/create_server.slint";
import { IServer, ServerFunctions } from "components/server.slint";
import { GlobalVars } from "common.slint";
import { StartScreen } from "screens/start.slint";
import { HostingFunctions, HostingAdapter } from "screens/hosting.slint";

export { GlobalVars }
export { 
    VideoState,
    BarialState,
    VideoFunctions, 
    ServerFunctions, 
    CreateServerFunctions,
    ControlPanelFunctions,
    HostingFunctions
}
export { 
    HostingAdapter,
    HomeAdapter,
    ControlPanelAdapter
}

export component MainWindow inherits Window {
    in-out property <int> page: 0;
    in-out property <image> video-frame;

    min-width: 550px;
    min-height: 500px;
    preferred-width: 725px;

    title: GlobalVars.app_name;
    padding: 0;
    forward-focus: key-handler;

    key-handler := FocusScope {
        key-pressed(event) => {
            if root.page == 2 {
                VideoFunctions.key_pressed(event);
            }
            accept
        }
        key-released(event) => {
            if root.page == 2 {
                VideoFunctions.key-released(event);
            }
            accept
        }

    }

    // LoginScreen {
    //     window-height: parent.height;
    //     set_current_subpage(page) => { root.page = page }
    //     back => { root.page = 0 }
    //     x: (0 - root.page) * (parent.width + parent.x + 2px);
    //     // visible: root.page == 0;
    //     // animate x { duration: 500ms; easing: ease-in-out; }
    // }
    StartScreen {
        height: parent.height;
        back => { root.page = 0 }
        set_current_subpage(page) => { root.page = page }
        visible: root.page == 0;
        x: (0 - root.page) * (parent.width + parent.x + 2px);
    }
    HomeScreen {
        height: parent.height;
        back => { root.page = 0 }
        set_current_subpage(page) => { 
            root.page = page;
            if root.page == 2 {
                key-handler.focus();
            }
        }
        visible: root.page == 1;
        x: (1 - root.page) * (parent.width + parent.x + 2px);
    }

    VideoScreen {
        video-frame: root.video-frame;
        set_current_subpage(page) => { root.page = page }
        back => { root.page = 0 }
        x: (2 - root.page) * (parent.width + parent.x + 2px);
        visible: root.page == 2;
    }
}