import { Screen } from "./common.slint";
import { VerticalBox, Button } from "std-widgets.slint";

export global VideoFunctions {
    pure callback mouse_move(/* x */ length, /* y */ length, /* pressed */ bool);
    pure callback click(/* x */ length, /* y */ length);
    pure callback modifiers_pressed(/* control */ bool, /* shift */ bool, /* alt */ bool, /* meta */ bool);
    pure callback key_pressed(KeyEvent);
    pure callback key_released(KeyEvent);
    pure callback scroll(/* x */ length, /* y */ length);
}

export component VideoScreen inherits Screen {
    in property <image> video-frame <=> image.source;

    VerticalBox {
        padding: 0;
        image := Image {
            width: 1440px;
            height: 900px;
            padding: 0;
            touch := TouchArea {
                clicked => {
                    VideoFunctions.click(touch.mouse-x, touch.mouse-y);
                }
                scroll-event(event) => {
                    VideoFunctions.scroll(event.delta-x, event.delta-y);
                    accept
                }
                pointer-event(event) => {
                   // debug(touch.mouse-x) // can use touch in combination with button right to detect right click
                }
                moved => {
                    VideoFunctions.mouse_move(touch.mouse-x, touch.mouse-y, self.pressed);
                    // control.x = touch.mouse-x - 12px;
                    // control.y = touch.mouse-y - 12px;
                }
            }
            // TouchArea { 
            //     control := Rectangle {
            //         x: 100px;
            //         y: 100px;
            //         width: 25px;
            //         height: 25px;
            //         border-radius: 5px;
            //         background: white;
            //     }
            // }
        }
    }
}