import { Screen, Theme } from "./common.slint";
import { VerticalBox, Button } from "std-widgets.slint";
import { MrialButton, ButtonType } from "common.slint";

export global VideoFunctions {
    pure callback mouse_move(/* x */ length, /* y */ length, /* pressed */ bool);
    pure callback click(/* x */ length, /* y */ length);
    pure callback modifiers_pressed(/* control */ bool, /* shift */ bool, /* alt */ bool, /* meta */ bool);
    pure callback key_pressed(KeyEvent);
    pure callback key_released(KeyEvent);
    pure callback scroll(/* x */ length, /* y */ length);

    pure callback connect();
    pure callback disconnect();
}

export component VideoScreen inherits Screen {
    in property <image> video-frame <=> image.source;
    in-out property <bool> cp_button_attached: false;

    VerticalBox {
        padding: 0;
        image := Image {
            width: 1440px;
            height: 900px;
            padding: 0;
            touch := TouchArea {
                clicked => {
                    if (touch.mouse-x > control_panel_button.x && 
                        touch.mouse-x < control_panel_button.x + control_panel_button.width && 
                        touch.mouse-y > control_panel_button.y && 
                        touch.mouse-y < control_panel_button.y + control_panel_button.height 
                    ) {
                        if (control-panel.visible) {
                            control_panel.visible = false; 
                        } else {
                            control_panel.visible = true; 
                        }
                    } else {
                        VideoFunctions.click(touch.mouse-x, touch.mouse-y);
                    }                    
                }
                scroll-event(event) => {
                    VideoFunctions.scroll(event.delta-x, event.delta-y);
                    accept
                }
                pointer-event(event) => {
                   // debug(touch.mouse-x) // can use touch in combination with button right to detect right click

                    if (touch.mouse-x > control_panel_button.x && 
                        touch.mouse-x < control_panel_button.x + control_panel_button.width && 
                        touch.mouse-y > control_panel_button.y && 
                        touch.mouse-y < control_panel_button.y + control_panel_button.height &&
                        event.kind == PointerEventKind.down
                    ) {
                        cp_button_attached = true; 
                    }

                    if (event.kind == PointerEventKind.up) {
                        cp_button_attached = false; 
                    }
                }
                moved => {
                    if (cp-button-attached) {
                        control_panel_button.x = touch.mouse-x - control_panel_button.width / 2;
                        control_panel_button.y = touch.mouse-y - control_panel_button.height / 2;
                        return;
                    }

                    VideoFunctions.mouse_move(touch.mouse-x, touch.mouse-y, self.pressed);
                }
            }
            control_panel := TouchArea {
                visible: false;
                x: control_panel_button.x + control_panel_button.width + 10px;
                y: control-panel-button.y;
                width: 200px;
                height: 275px;

                Rectangle {
                    x: 0px;
                    y: 0px;
                    width: parent.width;
                    height: parent.height;
                    border-radius: 10px;
                    border-width: 1px;
                    border-color: Theme.bg-secondary-color;
                    background: Theme.bg-primary-color;

                    VerticalBox {
                        alignment: LayoutAlignment.end;
                        MrialButton {
                            label: "Disconnect";
                            type: ButtonType.negative;
                            clicked => {
                                VideoFunctions.disconnect();
                                root.set_current_subpage(1);
                            }
                        }
                    }
                }
            }
            control_panel_button := Rectangle {
                x: 0px; 
                y: 0px; 
                width: 35px;
                height: 35px;
                border-radius: 7.5px;
                border-width: 1px;
                border-color: Theme.bg-secondary-color;
                background: Theme.bg-primary-color;
            }
        }
    }
}